name: build-test

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          targets: i686-unknown-linux-gnu

      - name: rustfmt
        run: |
          cargo fmt --all --check

      - name: clippy
        run: |
          cargo clippy --all-features --all-targets -- -D warnings

      - name: build
        run: |
          cargo build

      - name: test
        run: |
          ./scripts/test.sh

      - name: test i686-unknown-linux-gnu
        run: |
          sudo apt install gcc-multilib
          ./scripts/test.sh --target i686-unknown-linux-gnu
